#!/bin/bash

if [ $(whoami) != "root" ]
then 
	echo "Please run this program in root mode."
	exit 1
fi

#Determines the architecture type of the host system
if [ $HOSTTYPE != "x86_64" ]
then
	ARCH="i386"
else
	ARCH="x86_64"
fi

echo "$ARCH Distrobution detected....."

if [ -f /etc/redhat-release ] 
then 

	echo "Enabling RPMforge $ARCH repository......"

	if [ $ARCH = "i386" ]
	then
		wget http://packages.sw.be/rpmforge-release/rpmforge-release-0.3.6-1.el5.rf.i386.rpm
		rpm -Uvh rpmforge-release-0.3.6-1.el5.rf.i386.rpm
		rm -f rpmforge-release-0.3.6-1.el5.rf.i386.rpm
	else
		wget http://packages.sw.be/rpmforge-release/rpmforge-release-0.3.6-1.el5.rf.x86_64.rpm
		rpm -Uvh rpmforge-release-0.3.6-1.el5.rf.x86_64.rpm
		rm -f rpmforge-release-0.3.6-1.el5.rf.x86_64.rpm
	fi
	
	# libsys-gamin-perl or Sys::Gamin must be installed from source which can
	# be found here http://search.cpan.org/src/GARNACHO/Sys-Gamin-0.1/lib/Sys/Gamin.pm
	yum -y install monit heartbeat sqlite coreutils openssh-server tftp-server

	cp -rH haoscar-binaries/debian/etc/init.d/ha-oscar-filemon /etc/init.d/
	cp -rH haoscar-binaries/debian/etc/rc3.d/S99ha-oscar-filemon /etc/rc3.d/

	cp -rH haoscar-binaries/debian/etc/rc5.d/S99ha-oscar-filemon /etc/rc5.d/
	cp -rH haoscar-binaries/debian/usr /

	cp -rH haoscar-devel/debian/usr /

	cp -rH haoscar-libraries/debian/usr /

	cp -rH haoscar-utils/debian/usr /
else
	dpkg -i *.deb
	apt-get install -f
fi

exit 0
